# Site settings
title: Colin<br>Scott-Fleming
description: 'Django/AngularJS Marriage Counselor'
url: 'https://colinsf.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Colin Scott-Fleming'
  email: colin@scott-fleming.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  colinsf
  linkedin_username:  colin-scott-fleming-35aa463a

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
